header:
  stamp:
    sec: 75
    nanosec: 19736456
  frame_id: base_link
objects:
- existence_probability: 1.0
  classification:
  - label: 1
    probability: 1.0
  kinematics:
    pose_with_covariance:
      pose:
        position:
          x: 27.25480610704254
          y: 3.0
          z: 1.0116201556950424
        orientation:
          x: -0.9999999487927063
          y: -0.00017868745908125757
          z: -4.894258192809834e-05
          w: 0.0002609406071024785
      covariance:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    has_position_covariance: false
    orientation_availability: 2
    twist_with_covariance:
      twist:
        linear:
          x: 0.0
          y: 0.0
          z: 0.0
        angular:
          x: 0.0
          y: 0.0
          z: 0.0
      covariance:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    has_twist: false
    has_twist_covariance: false
  shape:
    type: 0
    footprint:
      points:
      - x: 29.55706214904785
        y: -0.37244275212287903
        z: 0.08434972167015076
      - x: 29.557241439819336
        y: 1.5591522455215454
        z: 0.08449546992778778
      - x: 24.95255470275879
        y: -0.37202876806259155
        z: 0.08389873802661896
      - x: 24.952733993530273
        y: 1.5595662593841553
        z: 0.08404448628425598
    dimensions:
      x: 4.6045098304748535
      y: 1.9315929412841797
      z: 1.8548461198806763