/**/tod_dummy_perception_pub:
  ros__parameters:
    publish_frequency: 10.0           # Hz
    output_topic_name: "~/output/detected_objects"
    position_covariance: 0.03         # Variance (m^2) applied to object position
    
